// Generated by CoffeeScript 1.8.0
(function() {
  var restrain_condition_html, restrain_example_html, restrain_figure_html, restrain_ids, restrain_img_html, restrain_range_html, restrain_type_html;

  this.restrain_html = function(restrain_json) {
    return [restrain_example_html(restrain_json), restrain_figure_html(restrain_json)];
  };

  restrain_example_html = function(restrain_json) {
    var a, id, ids, _i, _len;
    ids = restrain_ids(restrain_json);
    a = $("<a></a>");
    a.addClass("list-group-item");
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      id = ids[_i];
      a.append(restrain_img_html(id));
    }
    return a;
  };

  restrain_img_html = function(id) {
    return "<img src='http://cdn233.my-card.in/ygopro/pics/thumbnail/" + id + ".jpg'>";
  };

  restrain_ids = function(restrain_json) {
    var ids, number, type;
    type = restrain_json.type;
    if (type === 'card') {
      return Array(restrain_json.condition.number).fill(restrain_json.id);
    } else if (type === 'set') {
      ids = restrain_json.set.ids.slice(0);
      number = restrain_json.condition.number;
      if (number < ids.length) {
        return ids.slice(0, number);
      } else if (numbers <= ids.length * 2) {
        return ids.times(2).slice(0, number);
      } else {
        return ids.times(3).slice(0, number);
      }
    }
  };

  restrain_figure_html = function(restrain_json) {
    var a;
    a = $("<a></a>");
    a.addClass("list-group-item disabled");
    a.append(restrain_type_html(restrain_json));
    a.append(restrain_range_html(restrain_json.range));
    a.append(restrain_condition_html(restrain_json.condition, restrain_json.type));
    return a;
  };

  restrain_condition_html = function(condition_json, type) {
    var number, operator;
    operator = condition_json.operator;
    number = condition_json.number;
    return " <code>" + operator + "</code> <kbd class='" + type + "'>" + number + "</kbd>";
  };

  restrain_range_html = function(range_json) {
    if (range_json === "all") {
      return "";
    } else {
      return " <kbd class=\"" + range_json + "\">" + range_json + "</kbd>";
    }
  };

  restrain_type_html = function(restrain_json) {
    var name, type;
    type = restrain_json.type;
    name = restrain_json.name;
    return "<kbd class='" + type + "'>" + name + "</kbd>";
  };


  /*
        <div class="row">
          <div class="col-md-4">
              <div class="bs-example">
                  <img src="http://cdn233.my-card.in/ygopro/pics/thumbnail/60473572.jpg">
                  <img src="http://cdn233.my-card.in/ygopro/pics/thumbnail/33256280.jpg">
                  <img src="http://cdn233.my-card.in/ygopro/pics/thumbnail/7868571.jpg">
                  <img src="http://cdn233.my-card.in/ygopro/pics/thumbnail/69351984.jpg">
                  <img src="http://cdn233.my-card.in/ygopro/pics/thumbnail/18716735.jpg">
              </div>
              <figure class="highlight">
                  <kbd class="set">炼装</kbd> <code>>=</code> <kbd class="set">5</kbd>
              </figure>
          </div>
      </div>
   */

  Array.prototype.times = function(times) {
    var answer, item, _i, _len;
    answer = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      Array.prototype.push.apply(answer, Array(times).fill(item));
    }
    return answer;
  };

  this.help = function(index) {
    var jq;
    jq = restrain_html(ex[index].restrain);
    return $('div.row:last').append(jq);
  };

}).call(this);

//# sourceMappingURL=restrain.js.map
