// Generated by CoffeeScript 1.8.0
(function() {
  this.onCompileClick = function() {
    var text;
    text = $("textarea#inputDeckdef")[0].value;
    $.post("http://127.0.0.1:8080/deckidentifier/compiler", text, function(data, textStatus) {
      console.log(data);
      return generations_set_html(data);
    });
    return "";
  };

  $("document").ready(function() {
    return $("a#generate").click(function() {
      return onCompileClick();
    });
  });

}).call(this);

//# sourceMappingURL=toolbarAjax.js.map
