// Generated by CoffeeScript 1.8.0
(function() {
  this.switchToPreview = function() {};

  this.switchToAnswer = function() {};

  switchToPreview();

  this.setAnswerList = function(data) {
    var a, tag, _i, _len, _ref, _results;
    switchToAnswer();
    $("ul#answer-extra-message-list").empty();
    if (data === void 0) {
      $('#answer-deck-name').html("卡组辨识结果：谜之卡组");
    } else {
      $('#answer-deck-name').html("卡组辨识结果：" + data[0]);
    }
    _ref = data[1];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tag = _ref[_i];
      a = $("<a></a>");
      a.addClass("list-group-item");
      a.html(tag);
      _results.push($("ul#answer-extra-message-list").append(a));
    }
    return _results;
  };

}).call(this);

//# sourceMappingURL=answer.js.map
