// Generated by CoffeeScript 1.8.0
(function() {
  this.config = {
    "server": "/ygopro/analytics2/deckIdentifier/"
  };

  this.getServerURL = function(param) {
    showTempNotification('sending server ' + param + '...');
    return config.server + '/' + param;
  };

}).call(this);

//# sourceMappingURL=config.js.map
