// Generated by CoffeeScript 1.8.0
(function() {
  this.config = {
    "server": "/ygopro/analytics2/deckIdentifier"
  };

  this.getServerURL = function(param) {
    showTempNotification('sending server ' + param + '...');
    return config.server + '/' + param;
  };

  this.cardImgHTML = function(id) {
    return "<img src='http://ygo233.my-card.in/ygopro/pics/thumbnail/" + id + ".jpg'>";
  };

}).call(this);

//# sourceMappingURL=config.js.map
