// Generated by CoffeeScript 1.8.0
(function() {
  this.generateDeck = function(str) {
    var ex, focus, line, lines, main, side, _i, _len;
    lines = str.split(/\n|\r/);
    main = [];
    side = [];
    ex = [];
    focus = main;
    this.data.line = [];
    for (_i = 0, _len = lines.length; _i < _len; _i++) {
      line = lines[_i];
      line.trim();
      this.data.line.push(line);
      if (line.startsWith('#') && line !== "#extra") {
        continue;
      }
      if (line === "") {
        continue;
      }
      if (line === "#extra") {
        focus = ex;
      } else if (line === "!side") {
        focus = side;
      } else {
        focus.push(parseInt(line));
      }
    }
    return {
      'main': main,
      'side': side,
      'ex': ex
    };
  };

  this.generateDeckHTML = function(deck) {
    var card, html, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
    console.log(deck);
    html = "<p>";
    _ref = deck.main;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      card = _ref[_i];
      html += cardImgHTML(card);
    }
    html += "</p><p>";
    _ref1 = deck.side;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      card = _ref1[_j];
      html += cardImgHTML(card);
    }
    html += "</p><p>";
    _ref2 = deck.ex;
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      card = _ref2[_k];
      html += cardImgHTML(card);
    }
    html += "</p>";
    return $(html);
  };

}).call(this);

//# sourceMappingURL=deck.js.map
