// Generated by CoffeeScript 1.8.0
(function() {
  var fileInListClicked;

  this.setEditingFileList = function(data) {
    var a, li, str, _i, _len, _ref, _results;
    $('#dropdown-file-lists li').remove();
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      str = data[_i];
      _ref = generateLi(str), li = _ref[0], a = _ref[1];
      $('#dropdown-file-lists').append(li);
      _results.push(a.on('click', {
        name: str
      }, fileInListClicked));
    }
    return _results;
  };

  fileInListClicked = function(event) {
    $('#dropdown-editing-file')[0].childNodes[0].textContent = event.data.name;
    return $.ajax({
      url: getServerURL('product') + getAccessParameter(),
      data: {
        filename: event.data.name
      },
      success: function(data) {
        return setMainContent(data);
      }
    });
  };

}).call(this);

//# sourceMappingURL=editingFileList.js.map
