// Generated by CoffeeScript 1.8.0
(function() {
  this.generations_set_html = function(generations) {
    var a, generation, li, _i, _len, _ref;
    $("ul#list-classifications").empty();
    for (_i = 0, _len = generations.length; _i < _len; _i++) {
      generation = generations[_i];
      _ref = generateLi(generation.name), li = _ref[0], a = _ref[1];
      $("ul#list-classifications").append(li);
      a.click(generation, function(event) {
        $("button#dropdown-classification-list").html(event.data.name + "<span class=\"caret\"></span>");
        return classificationSetHTML(event.data);
      });
    }
    if (generations.length > 0) {
      return $("ul#list-classifications li a")[0].click();
    }
  };

  this.generateLi = function(name) {
    var a, li;
    li = $('<li></li>');
    li.attr('role', 'menuitem');
    a = $('<a></a>');
    a.attr('href', '#');
    a.html(name);
    li.append(a);
    return [li, a];
  };

}).call(this);

//# sourceMappingURL=generationsAjax.js.map
