// Generated by CoffeeScript 1.8.0
(function() {
  this.generationSetHTML = function(generations) {
    switchToPreview();
    this.generations = generations;
    return setGenerationHTML();
  };

  this.setGenerationHTML = function(filter) {
    var a, generation, li, targets, _i, _j, _len, _len1, _ref, _ref1;
    if (this.generations === null) {
      return;
    }
    if (!filter) {
      filter = "";
    }
    $("ul#list-classifications").empty();
    targets = [];
    _ref = this.generations;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      generation = _ref[_i];
      if (generation.name.includes(filter)) {
        targets.push(generation);
      }
    }
    for (_j = 0, _len1 = targets.length; _j < _len1; _j++) {
      generation = targets[_j];
      _ref1 = generateLi(generation.name), li = _ref1[0], a = _ref1[1];
      $("ul#list-classifications").append(li);
      a.click(generation, function(event) {
        $("button#dropdown-classification-list").html(event.data.name + "<span class=\"caret\"></span>");
        return classificationSetHTML(event.data);
      });
    }
    if (targets.length > 0) {
      return $("ul#list-classifications li a")[0].click();
    }
  };

  this.generateLi = function(name) {
    var a, li;
    li = $('<li></li>');
    li.attr('role', 'menuitem');
    a = $('<a></a>');
    a.attr('href', '#');
    a.html(name);
    li.append(a);
    return [li, a];
  };

}).call(this);

//# sourceMappingURL=generationsAjax.js.map
